FROM python:3.8
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /code
COPY . /code/
COPY ./deploy/celery/entrypoint.sh /

RUN pip config set global.index-url https://mirrors.cloud.tencent.com/pypi/simple
#ENV PIP_CONFIG_FILE ./deploy/gunicorn/pip.conf
RUN pip install -r requirements.txt

CMD ["celery" ,"-A", "cp_ws_project", "worker", "-l", "INFO"]